### ISSUE TITLE
conway game of life INDEX ERROR

### ISSUE THREAD

**Issue by alperyilmaz** [codereport/katas#1]
Hi, I really enjoyed your video on [Game of Life](https://www.youtube.com/watch?v=pMslgySQ8nc).

I installed `dyalog` and `ride` and tried your [code](https://github.com/codereport/katas/blob/master/ConwaysGameOfLife/ConwaysGameOfLife.apl) 

However, I got the following error:
```
INDEX ERROR
      {}{life∘←'.⌽'[⍵] ⋄ _←⎕DL÷8 ⋄ lifeIter ⍵}⍣≡t
                   ∧ 
```
Is it because of newer version of Dyalog? My Dyalog version is: `Dyalog APL/S-64 Version 18.0.40684`

**Comment by oraqlle** [comment]
I had the same issue with Dyalog Ride 18.0. I also had an issue where the randomly generated array for lifeInit produces random 1s and 2s not 1s and 0s

**Comment by aranjello** [comment]
I had the same issue, I think an update must have broken the code because the life init function no longer creates a binary array

**Comment by ericmeyers** [comment]
> Hi, I really enjoyed your video on [Game of Life](https://www.youtube.com/watch?v=pMslgySQ8nc).
> 
> I installed `dyalog` and `ride` and tried your [code](https://github.com/codereport/katas/blob/master/ConwaysGameOfLife/ConwaysGameOfLife.apl)
> 
> However, I got the following error:
> 
> ```
> INDEX ERROR
>       {}{life∘←'.⌽'[⍵] ⋄ _←⎕DL÷8 ⋄ lifeIter ⍵}⍣≡t
>                    ∧ 
> ```
> 
> Is it because of newer version of Dyalog? My Dyalog version is: `Dyalog APL/S-64 Version 18.0.40684`

Nah. It’s because he used 0 indexing. Just set ⎕IO←0 first.

**Comment by codereport** [comment]
Just fixed this in the code. Sorry for not noticing this issue until now. :pray:
